language: ruby
rvm:
- 2.3.3
env:
- URL=https://github.com/redpen-cc/redpen/releases/download/redpen-1.10.1
before_script:
- ls -la
- eval `ssh-agent -s`
- echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 600 ~/.ssh/config
- openssl aes-256-cbc -K $encrypted_b291a2cbdf5e_key -iv $encrypted_b291a2cbdf5e_iv
  -in travis_key.enc -out travis_key -d
- cp travis_key ~/.ssh/
- chmod 600 ~/.ssh/travis_key
- ssh-add ~/.ssh/travis_key
install:
- wget $URL/redpen-1.10.1.tar.gz
- tar xvf redpen-1.10.1.tar.gz
- export PATH=$PATH:$PWD/redpen-distribution-1.10.1/bin
script:
- git fetch git@github.com:testEnvOrganization/connection.git
- git branch -a
- git checkout master
- redpen -f asciidoc -r json -l 10000 --lang ja source/*.adoc > result.json
after_success:
- echo success.
- git fetch git@github.com:testEnvOrganization/connection.git
- git checkout -b gh-pages
- rm -f travis_key
- rm -rf redpen-*
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
notifications:
  slack:
    secure: FxeeMXQ35BmLztEQU6O9b4HZRVo6I5qlxSLsRLyU6yfR9Oi+FE5X69sjPp0w8oH0Pyjw8q/VEDjXK666sLocFx03TMiquU+HD6qJIQOT5Wmlxa0wzE+IkE/GzCjzgo43MqBJT4BRBdGdd+5bmaxK61Tj4ag3kskle7l/ObrK/0iDy9KufjduNCgDSkbskaMtWYs+SkWQapUoPyUw4ngBeNN4D8CeKP6ChA/uYvB6G2gkt+9lvYjv7ugaI0Gb8xBreTNKNjpFGswj5M1+tR2n2tUIeyCAn9RD7KOvz8uk36/i/FpUFJvXuVnpw7Obi1CQTzBUlW4Qm4h4rpKhnusCO0mrcMAD8030iL9jZFbPknmTyxwHJIA76PVjPEGp25aIlY9j2scqQjy9udpvoi3pVnrThQePodzFEFwTemZhBWc7HGhP4lyAlAka1ErZIK/sgM3B7BvWNWExpRfoJfH0yZ9XQMEwiw1mTZGAwUi2AvkmK3Qrw9d0Rz6PKMl/d+HdwZK3AGlcwN/MhgGyeqNXvlnvU0VoMv8CnHldUeAQ7kx7iXeATPo8u1hu4hl2miEc/8YICGikT4fiFodJKnvtfr4kKN478jv644X4sxbIMDDfJMhHtJf/QagXHzj+x9mI/rmTj16UfeTe3J0VBq+9HEhO8x9ljT5QGo3D0iEdG0I=
